# -*- coding: utf-8 -*-
"""Criar_CV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AJHp5jPNxP-CGyRM57W_EV81zgPi9P32
"""

import glob
import pandas as pd
import statistics
import os
from time import sleep

class Criar_CV:
    def __init__(self, caminho_pasta, saida_pasta):
        
        self.caminho_pasta = caminho_pasta
        self.saida_pasta = saida_pasta
        
        print('Script Python - Criar Coeficiente de Variação da Contagem Automática DEXCO')
        print('Version 1.0 (v1.0)')
        print('')
        sleep(2)
        pasta_txt = (caminho_pasta+'/*.txt')
        lista_arquivos_txt = []
        print('Os Arquivos ".txt" Estão Sendo Carregados...')
        sleep(4)
        print('O Arquivo Será Salvo no Caminho: '+"'"+saida_pasta+"'")
        sleep(5)
        for caminho_txt in glob.glob(pasta_txt):
            lista_arquivos_txt.append(caminho_txt)

        for i in range(len(lista_arquivos_txt)):
            df = pd.read_csv(lista_arquivos_txt[i], sep=" ", header=None, index_col=False)
            df = df.rename(columns={df.columns[0]:'Classe',df.columns[1]:'X_central',df.columns[2]:'Y_central',df.columns[3]:'Largura',df.columns[4]:'Altura',df.columns[5]:'Conf'})
            df['Largura'] = df['Largura'] * 1000
            df['Altura'] = df['Altura'] * 1000
            largura = df['Largura']
            altura = df['Altura']
            area = largura * altura
            df = df.assign(Area=area)
            desv_pad = statistics.pstdev(df['Area'])
            media = statistics.median(df['Area'])
            CV = (desv_pad / media) * 100
            df = df.assign(Calculo=CV)
            df = df.loc[:, ['Calculo']]
            df = df.iloc[[0]]

            nome_arquivo = str(lista_arquivos_txt[i]).split('.txt')[0].split('/')[-1:][0]
            df.to_csv(saida_pasta+'/CV_%(nomes_arquivo)s.txt'%{'nomes_arquivo': nome_arquivo}, index=False)
        print('Código Executado com Sucesso!!!')
        sleep(1)
        print('O Código Será Encerrado Automaticamente em 5 Segundos...')
        sleep(5)
    pass
